### ISSUE TITLE
could this work with matrix-voice esp32?

### ISSUE THREAD

**Issue by lostkohibu** [qnlbnsl/Matrix-IO#3]
after all i see it in the a earlier post, it should be. But after install the kernel mdules, the matrix voise doesn't work, no LED no listing on arcecord -l
my system: rassberry pi 3 B+ with bookworm 64Bit and Matrix-Voice ESP32

**Comment by lostkohibu** [comment]
oh sorry i found the answer in a ealier post. But i have a problem with the cronjob after the first reboot. I can't see the second script in the log.

**Comment by chiefymuc** [comment]
It works with esphome, see here: https://github.com/gnumpi/esphome_matrixio

**Comment by qnlbnsl** [comment]
it should work. Are you trying to use esp32 or just wanting to work with the voice on the rpi?

**Comment by lostkohibu** [comment]
@qnlbnsl at the moment i am trying to use esp32 with esphome and the matrix voice.

**Comment by qnlbnsl** [comment]
Can you try a 32bit version of debian then run the install. I haven't had time to fix and build the packages for the 64 bit version.

**Comment by qnlbnsl** [comment]
awesome! Sounds good! Closing this now.
